import { Server } from "mcp";
import { StdioServerTransport } from "@modelcontextprotocol/server-stdio";
import { Tool, TextContent } from "@modelcontextprotocol/shared-types";

// 하네스 구성 타입
interface HarnessConfig {
  name: string;
  framework: "jest" | "mocha" | "vitest" | "custom";
  language: "typescript" | "javascript" | "python";
  testDir: string;
  outputDir: string;
  parallel: boolean;
  timeout: number;
}

interface TestCase {
  name: string;
  description: string;
  setup?: string;
  execute: string;
  assertions: string[];
  teardown?: string;
}

// 하네스 빌더 클래스
class HarnessBuilder {
  private config: HarnessConfig;

  constructor(config: Partial<HarnessConfig>) {
    this.config = {
      name: config.name || "test-harness",
      framework: config.framework || "jest",
      language: config.language || "typescript",
      testDir: config.testDir || "./tests",
      outputDir: config.outputDir || "./test-results",
      parallel: config.parallel ?? true,
      timeout: config.timeout || 30000,
    };
  }

  /**
   * 하네스 설정 파일 생성
   */
  generateConfigFile(): string {
    const configs: Record<string, object> = {
      jest: {
        testEnvironment: "node",
        testMatch: ["**/__tests__/**/*.ts", "**/*.test.ts"],
        transform: { "^.+\\.ts$": "ts-jest" },
        moduleFileExtensions: ["ts", "js", "json"],
        collectCoverageFrom: [
          "src/**/*.ts",
          "!src/**/*.d.ts",
          "!src/**/index.ts",
        ],
        coverageThreshold: {
          global: { branches: 80, functions: 80, lines: 80, statements: 80 },
        },
      },
      mocha: {
        require: ["ts-node/register"],
        extension: ["ts"],
        spec: "tests/**/*.test.ts",
        timeout: this.config.timeout,
        bail: false,
      },
      vitest: {
        include: ["tests/**/*.test.ts"],
        environment: "node",
        globals: true,
        coverage: {
          provider: "v8",
          reporter: ["text", "json", "html"],
        },
      },
    };

    return JSON.stringify(configs[this.config.framework] || {}, null, 2);
  }

  /**
   * 테스트 케이스 템플릿 생성
   */
  generateTestTemplate(testCase: TestCase): string {
    if (this.config.language === "typescript") {
      return this.generateTypeScriptTest(testCase);
    }
    return this.generateJavaScriptTest(testCase);
  }

  private generateTypeScriptTest(testCase: TestCase): string {
    const assertions = testCase.assertions
      .map((a) => `    expect(${a}).toBeTruthy();`)
      .join("\n");

    return `describe('${testCase.name}', () => {
  ${testCase.setup ? `beforeEach(() => {\n    ${testCase.setup}\n  });` : ""}
  
  it('${testCase.description}', async () => {
    // Setup
    ${testCase.setup || "// No setup"}
    
    // Execute
    ${testCase.execute}
    
    // Assertions
${assertions}
  });
  
  ${testCase.teardown ? `afterEach(() => {\n    ${testCase.teardown}\n  });` : ""}
});`;
  }

  private generateJavaScriptTest(testCase: TestCase): string {
    const assertions = testCase.assertions
      .map((a) => `    expect(${a}).toBeTruthy();`)
      .join("\n");

    return `describe('${testCase.name}', () => {
  it('${testCase.description}', async () => {
    // Execute
    ${testCase.execute}
    
    // Assertions
${assertions}
  });
});`;
  }

  /**
   * 통합 테스트 하네스 생성
   */
  generateIntegrationHarness(
    testCases: TestCase[],
    setupCode: string = "",
    teardownCode: string = ""
  ): string {
    const tests = testCases
      .map((tc) => this.generateTestTemplate(tc))
      .join("\n\n");

    return `// Integration Test Harness
// Generated by Harness Builder MCP

${this.config.language === "typescript" ? "import { describe, it, expect, beforeAll, afterAll } from '@jest/globals';" : ""}

describe('Integration Test Suite', () => {
  ${setupCode ? `beforeAll(async () => {\n    ${setupCode}\n  });` : ""}
  
${tests}

  ${teardownCode ? `afterAll(async () => {\n    ${teardownCode}\n  });` : ""}
});`;
  }

  /**
   * 성능 테스트 하네스 생성
   */
  generatePerformanceHarness(
    testCases: TestCase[],
    threshold: number = 100
  ): string {
    return `// Performance Test Harness
describe('Performance Tests', () => {
  ${testCases
    .map(
      (tc) => `
  it('${tc.description} should complete within ${threshold}ms', async () => {
    const start = performance.now();
    ${tc.execute}
    const end = performance.now();
    expect(end - start).toBeLessThan(${threshold});
  });`
    )
    .join("\n")}
});`;
  }

  /**
   * 병렬 실행 설정 생성
   */
  generateParallelConfig(): string {
    if (this.config.framework === "jest") {
      return JSON.stringify(
        {
          maxWorkers: "50%",
          testTimeout: this.config.timeout,
          bail: 1,
        },
        null,
        2
      );
    }
    return "{}";
  }

  /**
   * 하네스 상태 리포트
   */
  getHarnessStatus(): object {
    return {
      name: this.config.name,
      framework: this.config.framework,
      language: this.config.language,
      testDir: this.config.testDir,
      outputDir: this.config.outputDir,
      parallel: this.config.parallel,
      timeout: this.config.timeout,
      generatedAt: new Date().toISOString(),
    };
  }
}

// MCP 서버 설정
const server = new Server(
  {
    name: "harness-builder-mcp",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// 도구 1: 하네스 초기화
server.setRequestHandler({ name: "list_tools", kind: "request" }, async () => {
  const tools: Tool[] = [
    {
      name: "init_harness",
      description:
        "하네스 프로젝트를 초기화합니다. 테스트 프레임워크, 언어, 디렉토리 등을 설정합니다.",
      inputSchema: {
        type: "object" as const,
        properties: {
          name: {
            type: "string",
            description: "하네스 프로젝트 이름",
          },
          framework: {
            type: "string",
            enum: ["jest", "mocha", "vitest", "custom"],
            description: "테스트 프레임워크",
          },
          language: {
            type: "string",
            enum: ["typescript", "javascript", "python"],
            description: "프로그래밍 언어",
          },
          testDir: {
            type: "string",
            description: "테스트 디렉토리 경로",
          },
          outputDir: {
            type: "string",
            description: "결과 출력 디렉토리",
          },
          parallel: {
            type: "boolean",
            description: "병렬 실행 여부",
          },
        },
        required: ["name", "framework"],
      },
    },
    {
      name: "generate_test_case",
      description:
        "테스트 케이스 템플릿을 생성합니다. 테스트 이름, 설명, 실행 코드를 지정할 수 있습니다.",
      inputSchema: {
        type: "object" as const,
        properties: {
          testName: {
            type: "string",
            description: "테스트 이름",
          },
          description: {
            type: "string",
            description: "테스트 설명",
          },
          execute: {
            type: "string",
            description: "실행할 코드",
          },
          assertions: {
            type: "array",
            items: { type: "string" },
            description: "단언(assertion) 리스트",
          },
          setup: {
            type: "string",
            description: "세팅 코드 (선택사항)",
          },
          teardown: {
            type: "string",
            description: "정리 코드 (선택사항)",
          },
        },
        required: ["testName", "description", "execute", "assertions"],
      },
    },
    {
      name: "generate_integration_suite",
      description:
        "여러 테스트 케이스를 통합한 테스트 스위트를 생성합니다.",
      inputSchema: {
        type: "object" as const,
        properties: {
          testCases: {
            type: "array",
            description: "테스트 케이스 배열",
          },
          setupCode: {
            type: "string",
            description: "전체 세팅 코드",
          },
          teardownCode: {
            type: "string",
            description: "전체 정리 코드",
          },
        },
        required: ["testCases"],
      },
    },
    {
      name: "generate_performance_harness",
      description:
        "성능 테스트 하네스를 생성합니다. 응답 시간 제한을 설정할 수 있습니다.",
      inputSchema: {
        type: "object" as const,
        properties: {
          testCases: {
            type: "array",
            description: "테스트 케이스 배열",
          },
          threshold: {
            type: "number",
            description: "성능 임계값 (ms)",
          },
        },
        required: ["testCases"],
      },
    },
    {
      name: "get_harness_config",
      description: "현재 하네스 설정을 조회합니다.",
      inputSchema: {
        type: "object" as const,
        properties: {},
      },
    },
  ];

  return { tools };
});

// 도구 2: 요청 처리
server.setRequestHandler(
  { name: "call_tool", kind: "request" },
  async (request) => {
    const { name, arguments: args } = request;

    try {
      let result: object | string;
      const builder = new HarnessBuilder(args as Partial<HarnessConfig>);

      switch (name) {
        case "init_harness":
          result = {
            message: `하네스 "${args.name}" 초기화 완료`,
            config: builder.getHarnessStatus(),
            configFile: builder.generateConfigFile(),
          };
          break;

        case "generate_test_case":
          result = {
            message: "테스트 케이스 생성 완료",
            testCode: builder.generateTestTemplate({
              name: args.testName,
              description: args.description,
              execute: args.execute,
              assertions: args.assertions,
              setup: args.setup,
              teardown: args.teardown,
            }),
          };
          break;

        case "generate_integration_suite":
          result = {
            message: "통합 테스트 스위트 생성 완료",
            suiteCode: builder.generateIntegrationHarness(
              args.testCases,
              args.setupCode,
              args.teardownCode
            ),
          };
          break;

        case "generate_performance_harness":
          result = {
            message: "성능 테스트 하네스 생성 완료",
            performanceCode: builder.generatePerformanceHarness(
              args.testCases,
              args.threshold || 100
            ),
          };
          break;

        case "get_harness_config":
          result = builder.getHarnessStatus();
          break;

        default:
          throw new Error(`알 수 없는 도구: ${name}`);
      }

      return {
        content: [
          {
            type: "text" as const,
            text: JSON.stringify(result, null, 2),
          },
        ],
      };
    } catch (error) {
      return {
        content: [
          {
            type: "text" as const,
            text: `오류 발생: ${error instanceof Error ? error.message : String(error)}`,
          },
        ],
        isError: true,
      };
    }
  }
);

// 서버 시작
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("[Harness Builder MCP] Server running on stdio");
}

main().catch(console.error);
